name: excercise-ghapi
on: issue_comment

permissions:
  issues: write
  pull-requests: write

jobs:
  ghapi-exercise:
  
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest

    steps:        
    - name: install dependencies
      run: pip install ghapi 

    - name: see payload # this step is for debugging purposes only, so you can see the payload. 
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
      
    - name: Make a comment
      shell: python
      run: |
        import os
        run_id = od.environ['PR_COMMENT'].replace('/wandb', '')
        print(run_id)
              
      env:
        PR_COMMENT: ${{ github.event.comment.body }}
