name: GitHub Actions Demo

on: [push]

jobs:
  Wandb-cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello
        run: |
          echo "hello world"
      - name: run python script
        run: | 
          pip install -r requirements.txt
          python ci.py
# use ghapi to create a label bug
# trigger is a comment not a pr? if comment /bug exists label the comment as bug


   
