name: trigger-demo
on:
  push:
    branches:
      - main #on main
  pull_request:
  workflow_dispatch:

jobs:
  trigger-demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
# Adding protection is necessary to make sure the status must pass before merging to a branch